name: 构建apk

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  build:
    name: "构建apk"
    runs-on: ubuntu-latest
    steps:
    - name: 1 安装依赖
      run: |
        sudo apt update && sudo apt install -y libarchive-tools
    - name: 2 克隆仓库
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: 3 gradle验证
      uses: gradle/wrapper-validation-action@v2
      
    - name: 4 java配置
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: 5 恢复缓存
      uses: actions/cache@v4
      with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

          restore-keys: |
            ${{ runner.os }}-gradle-

    - name: 6. 构建
      run: ./gradlew assembleDebug
    
    - name: 7. 上传apk
      uses: actions/upload-artifact@v4
      with:
        name: winlator-arm64-v8-debug
        path: ./app/build/outputs/apk/debug/app-debug.apk

    # - name: Update Nightly Release
    #   uses: andelf/nightly-release@main
    #   if: github.repository == 'termux/termux-x11' && github.ref == 'refs/heads/master'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: nightly
    #     name: 'Nightly Release $$'
    #     draft: false
    #     prerelease: false
    #     body: |
    #       This is a nightly release of the termux-x11 app.
    #       Based on ${{ github.sha }}
    #     files: |
    #       ./app/build/outputs/apk/debug/app-*-debug.apk
    #       ./app/build/outputs/apk/debug/shell-loader-nightly.apk
    #       ./app/build/outputs/apk/debug/termux-x11-*-all.deb
    #       ./app/build/outputs/apk/debug/termux-x11-*-any.pkg.tar.xz
